# Generated by Django 5.2.8 on 2025-11-12 19:27

import users.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.user_manager.UserManager()),
            ],
        ),
    ]
