# Generated by Django 5.1.6 on 2025-11-13 14:33

import django_resized.forms
import utils.photo_path
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[300, 300],
                upload_to=utils.photo_path.get_photo_path,
            ),
        ),
    ]
