# Generated by Django 5.1.6 on 2025-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_post_header_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="teaser",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
